#!/usr/bin/env bash
# publish.sh — mirror the on-disk dist/ into the GitHub-safe public repo.
#
# What it does:
#   1. arch-verify every binary (refuse to publish anything mislabeled),
#   2. copy dist/ → DEST (default ../le-harnais-v0-public), minus heavy build scratch,
#   3. SPLIT any file > 45 MB into ≤45 MB parts + a .sha256 + a join.sh (GitHub warns at
#      50 MB / blocks at 100 MB), and remove the oversized original from the mirror,
#   4. assert no file > 50 MB remains, then print the git status of DEST (it does NOT commit).
#
#   ./dist/publish.sh [DEST]
set -uo pipefail
cd "$(dirname "$0")/.."                       # repo root
SRC="$PWD/dist"
DEST="${1:-$PWD/../le-harnais-v0-public}"
LIMIT_SPLIT=$((45*1024*1024))                 # split above 45 MB
LIMIT_ASSERT=$((50*1024*1024))                # fail if anything > 50 MB survives

[ -d "$DEST" ] || { echo "DEST '$DEST' does not exist"; exit 1; }

echo ">> arch-verify (no mislabeled binary, no undeclared shared-lib dep)"
"$SRC/verify-arch.sh" || { echo "ABORT: mislabeled binary or undeclared/unauditable linked libs — fix before publishing."; exit 1; }

echo ">> mirror dist/ → $DEST"
# copy everything on disk except heavy/local build scratch. rsync if available, else cp.
# CRITICAL: --exclude '.git/' (NOT --delete-excluded) so the DEST repo's .git is never touched.
# --delete cleans stale dist files; excluded paths (.git, our own parts/join.sh) are protected.
EXC=(--exclude '.git/' --exclude '_staging/' --exclude '_gguf/' --exclude 'vendor/' --exclude '*.part-*' --exclude '*.sha256' --exclude 'join.sh')
if command -v rsync >/dev/null; then
  rsync -a --delete "${EXC[@]}" "$SRC"/ "$DEST"/
else
  cp -a "$SRC"/. "$DEST"/ ; rm -rf "$DEST/_staging" "$DEST/_gguf" "$DEST/vendor"
fi

# the beautified public README lives at dist/PUBLIC-README.md → becomes DEST/README.md
[ -f "$SRC/PUBLIC-README.md" ] && cp "$SRC/PUBLIC-README.md" "$DEST/README.md"
# carry the shared logo
[ -f "$PWD/assets/logo.svg" ] && { mkdir -p "$DEST/assets"; cp "$PWD/assets/logo.svg" "$DEST/assets/"; }
# the README swap above invalidates the mirrored top-level SHA256SUMS —
# regenerate it against DEST's actual files so `sha256sum -c` passes there.
if [ -f "$DEST/SHA256SUMS" ]; then
  ( cd "$DEST" && awk '{print $2}' SHA256SUMS | xargs sha256sum > SHA256SUMS.new \
      && mv SHA256SUMS.new SHA256SUMS && sha256sum -c SHA256SUMS --quiet ) \
    || { echo "SHA256SUMS regeneration FAILED in $DEST"; exit 1; }
fi

echo ">> split files > 45 MB"
JOIN="$DEST/join.sh"
split_any=0
REASSEMBLED=()                                 # rel paths of split targets → into DEST/.gitignore
while IFS= read -r -d '' f; do
  sz=$(stat -c%s "$f" 2>/dev/null || stat -f%z "$f")
  [ "$sz" -le "$LIMIT_SPLIT" ] && continue
  split_any=1
  base="$(basename "$f")"
  echo "   splitting $base ($(numfmt --to=iec "$sz"))"
  ( cd "$(dirname "$f")" && split -b 45m -d "$base" "${base}.part-" && { sha256sum "$base" > "${base}.sha256" 2>/dev/null || shasum -a 256 "$base" > "${base}.sha256"; } )
  REASSEMBLED+=("/${f#$DEST/}")
  rm -f "$f"                                   # drop the oversized original from the mirror
done < <(find "$DEST" -type f ! -name '*.part-*' ! -name '*.sha256' -print0)

# a .gitignore so a locally-run join.sh (which recreates the whole binaries) never dirties
# the repo. Only the ≤45 MB parts + .sha256 + join.sh are tracked. Derive the ignore list
# from EVERY .sha256 sidecar in the mirror (not just what THIS run split) so pre-existing
# split targets — e.g. a macOS binary another agent split — are covered too.
{
  echo "# generated by dist/publish.sh — reassembled (join.sh) binaries are local artifacts"
  while IFS= read -r -d '' s; do t="${s%.sha256}"; echo "/${t#$DEST/}"; done \
    < <(find "$DEST" -name '*.sha256' -print0 | sort -z)
} > "$DEST/.gitignore"

if [ "$split_any" = 1 ]; then
  cat > "$JOIN" <<'SH'
#!/usr/bin/env bash
# Reassemble every split binary in this tree: cat parts → original, verify sha256, chmod +x.
# Portable across bash 3.2 (stock macOS) and Linux — uses `find`, not globstar (bash 4+).
set -euo pipefail
cd "$(dirname "$0")"
while IFS= read -r sha; do
  d="$(dirname "$sha")"; base="$(basename "$sha" .sha256)"
  parts=("$d/$base".part-*)
  [ -e "${parts[0]}" ] || { echo "no parts for $base"; continue; }
  cat "${parts[@]}" > "$d/$base"
  ( cd "$d" && { sha256sum -c "$(basename "$sha")" 2>/dev/null || shasum -a 256 -c "$(basename "$sha")"; } )
  chmod +x "$d/$base"
  echo "reassembled $d/$base"
done < <(find . -type f -name '*.sha256')
SH
  chmod +x "$JOIN"
  echo "   wrote $JOIN"
fi

echo ">> assert nothing > 50 MB survives in the mirror"
BIG="$(find "$DEST" -type f -size +${LIMIT_ASSERT}c -not -path '*/.git/*' 2>/dev/null)"
if [ -n "$BIG" ]; then echo "FAIL: files over 50 MB remain:"; echo "$BIG"; exit 1; fi
echo "   OK — largest files:"; find "$DEST" -type f -not -path '*/.git/*' -printf '%s\t%p\n' 2>/dev/null | sort -rn | head -5 | awk '{printf "     %s\t%s\n", $1, $2}'

echo
echo ">> git status of $DEST (review, then commit yourself — publish.sh does NOT commit):"
git -C "$DEST" add -A && git -C "$DEST" status --short | head -30
echo "done."
